### ISSUE TITLE
How to train the ESRGAN on my own dataset

### ISSUE THREAD

**Issue by Techzist16** [Lornatang/ESRGAN-PyTorch#22]
Please provide me a guideline how to train ESRGAN network on my own dataset for upscaling factor 2, 3, 4?

**Comment by Lornatang** [comment]
See `data/README.md` ~
This is an example of data set creation at the time of recurrence

**Comment by Techzist16** [comment]
@Lornatang Okay. One more question I have is, during the training, should I first train on the RRDBnet network, and then after that go on to training on the ESRGAN network?

**Comment by Lornatang** [comment]
yeah. First train RRDB network.

**Comment by Techzist16** [comment]
I have got this error while training the RRDBnet using this following command:
 **python train_rrdbnet.py**  
`Traceback (most recent call last):
  File "train_rrdbnet.py", line 22, in <module>
    from torch.cuda import amp
ImportError: cannot import name 'amp'
`
Pytorch  and cuda toolkit version I have installed: 1.4 & 10.

**Comment by Lornatang** [comment]
Please upgrade PyTorch to version 1.7.0 or higher.
This will greatly reduce your training time.

**Comment by Techzist16** [comment]
Now, getting this error. Is this the python version error?
> Traceback (most recent call last):
  File "train_rrdbnet.py", line 28, in <module>
    from dataset import CUDAPrefetcher, TrainValidImageDataset, TestImageDataset
  File "/home/ESRGAN-PyTorch-main/dataset.py", line 24, in <module>
    import imgproc
  File "/home/ESRGAN-PyTorch-main/imgproc.py", line 502, in <module>
    scale_factor: float = 1.0) -> np.ndarray:
**TypeError: 'type' object is not subscriptable**

**Comment by Techzist16** [comment]
Thank you so much for your prompt reply. Now, I'm getting this pytorch module problem after updating the pytorch version to 1.8 (cuda version: 11) and torchvision .9

> Traceback (most recent call last):
  File "./train_rrdbnet.py", line 30, in <module>
    from model import Generator
  File "/home/ESRGAN-PyTorch-main/model.py", line 18, in <module>
    from torchvision.models.feature_extraction import create_feature_extractor
**ModuleNotFoundError: No module named 'torchvision.models.feature_extraction'**

Please help me solve this error.

**Comment by Lornatang** [comment]
Sorry, I forgot, torchvision.models.feature_extraction is supported by PyTorch1.11.0~~~, please upgrade PyTorch to 1.11.0, this is my mistake, sorry

**Comment by Techzist16** [comment]
Got this error while testing using : **python ./test.py**

> Traceback (most recent call last):
  File "./test.py", line 111, in <module>
    main()
  File "./test.py", line 33, in main
    checkpoint = torch.load(config.model_path, map_location=lambda storage, loc: storage)
AttributeError: module 'config' has no attribute 'model_path'

But I have assigned the model path in config.py file:

`if mode == "test":
    # Test data address
    lr_dir = f"./data/Set5/LRbicx{upscale_factor}"
    sr_dir = f"./results/test/{exp_name}"
    hr_dir = f"./data/Set5/GTmod12"

    #model_path = "./results/pretrained_models/RRDBNet_x4-DFO2K-2e2a91f4.pth.tar"
    model_path = "./results/ESRGAN_baseline/g_best.pth.tar`

**Comment by Techzist16** [comment]
Hello @Lornatang , I trained and tested the ESRGAN code on my dataset, however the results were distorted super-resolved images. I used around 700 images for training and used the same epoch as  did for natural images. Please see attached the result I obtained. What is the reason of this sort of distortion? It would be very kind of you if you could assist me in resolving this problem.
![baseballfield408_SR](https://user-images.githubusercontent.com/37292478/174436160-0e9c6240-27a5-4e27-be92-acc6c64f2911.png)

**Comment by Lornatang** [comment]
Please tell me LR size, SR size, HR size?
Training size ?

**Comment by Techzist16** [comment]
The sizes of  LR, HR and SR in testing are given below:
LR size= 64X64 
SR size= 256X256
HR size= 256X256

However, the dataset was originally 256X256 size and was cropped to size of 224X224 for training.

**Comment by Lornatang** [comment]
You should be that the number of Epochs is too small. The Epochs in the code are tested on the DFO2K dataset. You set a larger point to ensure that there are 1,000,000 backpropagations

**Comment by Techzist16** [comment]
> You should be that the number of epochs is too small. The epochs in the code are tested on the DFO2K dataset. You set a larger epochs to ensure that there are 1,000,000 backpropagations.

Okay. Thank you so much.

**Comment by Kpriyansh** [comment]
Hi @Techzist16 need a small help from you regarding training and testing the code?

**Comment by Techzist16** [comment]
> > You should be that the number of epochs is too small. The epochs in the code are tested on the DFO2K dataset. You set a larger epochs to ensure that there are 1,000,000 backpropagations.
> 
> Okay. Thank you so much.

I have the epochs for the training of the RRDB network set at around 10,000, however after epoch 120, the validation and testing PSNR become almost constant. Larger epochs do not boost training efficiency in my case.

**Comment by Techzist16** [comment]
> Hi @Techzist16 need a small help from you regarding training and testing the code?

Yes, tell me.

**Comment by Kpriyansh** [comment]
@Techzist16 are you using google colab for training ? or some other platform

**Comment by Techzist16** [comment]
> @Techzist16 are you using google colab for training ? or some other platform

I have my own GPU-equipped Linux-based system.

**Comment by Lornatang** [comment]
> > > You should be that the number of epochs is too small. The epochs in the code are tested on the DFO2K dataset. You set a larger epochs to ensure that there are 1,000,000 backpropagations.
> > 
> > 
> > Okay. Thank you so much.
> 
> I have the epochs for the training of the RRDB network set at around 10,000, however after epoch 120, the validation and testing PSNR become almost constant. Larger epochs do not boost training efficiency in my case. @Lornatang

There are learning rate adjustments in the training process. It can be reduced in two ways, one is with the number of epochs, and the other is manually set. Lowering the learning rate usually results in higher accuracy.

**Comment by Lornatang** [comment]
This feature has not been added yet, it will be added later

**Comment by Lornatang** [comment]
If I have time...

**Comment by shshojaei** [comment]
> The sizes of LR, HR and SR in testing are given below: LR size= 64X64 SR size= 256X256 HR size= 256X256
> 
> However, the dataset was originally 256X256 size and was cropped to size of 224X224 for training.

Hi, the original DIV2K dataset resolution is 1000*2000, how did you resize it to 256*256? Is there any code for this?

**Comment by Lornatang** [comment]
In `scripts` dir, see `run.py`

**Comment by shshojaei** [comment]
> In `scripts` dir, see `run.py`

Sorry right now i deleted my question. Yes thats right but run.py extract patches with the same size 224X224, not the DIV2K dataset with the same size 256X256.

**Comment by Lornatang** [comment]
Try change this? 
`--image_size 256 --step 128`

**Comment by shshojaei** [comment]
> Try change this? `--image_size 256 --step 128`

My problem is that my images are 1000X2000, so there are a lot of patches extracted for each image and Collab Pro can't handle it.  When I saw this comment about the size of the images, I thought that because your images are 256 x 256, fewer patches will be produced.  If I do what you said, the patches will be more than what they are now, And because of the explanation you wrote in the data folder, I think the names of the images will be changed with this. Am I wrong?  Something like 0001_0001_0001.  Doesn't it cause a problem?

**Comment by Lornatang** [comment]
You can also not process this images , but it will put a lot of pressure on IO data reading. The file name is just a pronoun and does not represent any specific meaning.

**Comment by shshojaei** [comment]
> You can also not process this images , but it will put a lot of pressure on IO data reading. The file name is just a pronoun and does not represent any specific meaning.

Thanks for your advice, i decided to extract 256X256 patches. I have another question, what is the image size = 128 in config.py? because at the end of the first epoch, i get the following error: `Supplied images have different sizes torch.Size([1, 3, 276, 276]) and torch.Size([1, 3, 504, 504])`

**Comment by shshojaei** [comment]
> > You can also not process this images , but it will put a lot of pressure on IO data reading. The file name is just a pronoun and does not represent any specific meaning.
> 
> Thanks for your advice, i decided to extract 256X256 patches. I have another question, what is the image size = 128 in config.py? because at the end of the first epoch, i get the following error: `Supplied images have different sizes torch.Size([1, 3, 276, 276]) and torch.Size([1, 3, 504, 504])`

I think `image_size` should be `64` in my case if it's LR image size, but This error does not change by resizing the LR image size.

**Comment by Lornatang** [comment]
`config.py` file, --image_size = <GT image size>

**Comment by Lornatang** [comment]
Many interesting things have been updated in the latest code, you can use it, and submit a new issue if you have any problems

**Comment by YAN287-hub** [comment]
> 非常感谢您帮我解决问题。我一定会降低学习率。另外，我想把**alpha**值从 0.2 改成 1。请问我需要在代码的哪个位置修改？
> 
> ![image](https://user-images.githubusercontent.com/37292478/174735347-2dbb5dd3-d109-46e3-a08b-5de2dd8314b7.png) [@Lornatang](https://github.com/Lornatang)

你好我是否可以请教一些关于ESRGAN的问题
